# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{javascript_auto_include}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Ulf Moehring}]
  s.date = %q{2011-06-10}
  s.description = %q{Rails helper for automatically including javascript files. Looks up assets in public/javascripts based on the current controller/action pair.}
  s.email = %q{hello@ulfmoehring.net}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/javascript_auto_include.rb",
    "lib/javascript_auto_include/dependency.rb",
    "lib/javascript_auto_include/helpers/action_controller.rb",
    "lib/javascript_auto_include/helpers/action_view.rb",
    "lib/javascript_auto_include/source_file.rb",
    "spec/dependency_spec.rb",
    "spec/javascript_auto_include_spec.rb",
    "spec/javascript_auto_include_tag_spec.rb",
    "spec/source_file_spec.rb",
    "spec/spec_helper.rb",
    "spec/testbed/Gemfile",
    "spec/testbed/Gemfile.lock",
    "spec/testbed/Rakefile",
    "spec/testbed/config.ru",
    "spec/testbed/config/application.rb",
    "spec/testbed/config/boot.rb",
    "spec/testbed/config/dependencies/another_fake_controller.yml",
    "spec/testbed/config/dependencies/application.yml",
    "spec/testbed/config/dependencies/fake_controller.yml",
    "spec/testbed/config/dependencies/jquery.yml",
    "spec/testbed/config/dependencies/rails.yml",
    "spec/testbed/config/environment.rb",
    "spec/testbed/config/environments/development.rb",
    "spec/testbed/config/environments/production.rb",
    "spec/testbed/config/environments/test.rb",
    "spec/testbed/config/routes.rb",
    "spec/testbed/log/development.log",
    "spec/testbed/log/production.log",
    "spec/testbed/log/server.log",
    "spec/testbed/log/test.log",
    "spec/testbed/public/javascripts/another_fake_controller.js",
    "spec/testbed/public/javascripts/application.js",
    "spec/testbed/public/javascripts/fake_controller.js",
    "spec/testbed/public/javascripts/jquery.js",
    "spec/testbed/public/javascripts/jquery.ui.core.js",
    "spec/testbed/public/javascripts/jquery.ui.core.min.js",
    "spec/testbed/public/javascripts/jquery.ui.mouse.js",
    "spec/testbed/public/javascripts/jquery.ui.mouse.min.js",
    "spec/testbed/public/javascripts/jquery.ui.widget.js",
    "spec/testbed/public/javascripts/jquery.ui.widget.min.js",
    "spec/testbed/public/javascripts/rails.js"
  ]
  s.homepage = %q{http://github.com/paceline/javascript_auto_include}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{Rails helper for automatically including javascript files}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 3.0.7"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 2.6.rc"])
    else
      s.add_dependency(%q<rails>, ["~> 3.0.7"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 2.6.rc"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 3.0.7"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 2.6.rc"])
  end
end

